version: "3"

services: 
  instaclone-app:
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        NODE_ENV: development
        WORKDIR: /app
        DISTANCE: src
    ports:
      - "4000:4000" # node app
      - "5555:5555" # prisma studio
    volumes: 
      - ./src:/app/dist
      - ./prisma:/app/prisma
      - ./nodemon.json:/app/nodemon.json
    environment: 
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgresql://pgadmin:pgadmin12345@instaclone-postgres.cc8bmldzeb01.ap-northeast-2.rds.amazonaws.com:5432/instaclone-postgres?schema=public
      - SECRET_KEY=DnRT21YWsoAMsRUDep8VDjcQlGQtLxY9
      - AWS_KEY=AKIAVJY3TDJNHNG3XNMB
      - AWS_SECRET=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
      - AWS_BUCKET=my-instaclone-uploads
      - AWS_REGION=ap-northeast-2
    command: bash -c "npx prisma studio | npm run dev" 
